variables:  
  - group: SharedGroup  
  - name: funcAppName
    value: demohotels
  - name: rgName
    value: "rg-$(funcAppName)-$(environmentName)"
  - name: rgLocation
    value: Australia Southeast
  - name: createNewRg
    value: true
  - name: deploymentsOlderThan
    value: -1
  - name: sgName
    value: "sgcc$(funcAppName)$(environmentName)"    
  - name: sgType
    value: Standard_LRS    
  - name: sgTier
    value: Standard
  - name: planName
    value: "plan-$(funcAppName)-$(environmentName)"
  - name: planSku
    value: Y1        
  - name: planTier
    value: Dynamic
  - name: commonRgName
    value: rg-cc-platform  