parameters:
  projectFiles: ''

steps:

- task: UseDotNet@2
  displayName: 'Installing .NET SDK 6.x'
  inputs:
    packageType: 'sdk'    
    version: '6.0.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'    
    projects: |
      ${{parameters.projectFiles}}

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build --no-restore'    
    projects: |
      ${{parameters.projectFiles}}
    arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration Release'

- task: ArchiveFiles@2
  displayName: 'Archive Files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  displayName: Create function app artifact
  artifact: funcapp 

- publish: $(Build.Repository.LocalPath)/Deploy/Resources
  displayName: Create IaC template artifacts
  artifact: deploy 