name: Demo.Serverless.Hotels
concurrency: demo-serverless-hotels

on:
  push:
    branches:
      - main
      - feature/**

  workflow_dispatch: 

env:
  PackagePath: './published'
  functionAppName: 'ccfunkyhotels'

jobs:
  provision:
    name: 'Setup Azure Infrastructure'    
    runs-on: ubuntu-latest    

    env:
      ResourceGroupName: 'rg-cc-funky-hotels-dev'
      ResourceGroupLocation: 'australiasoutheast'            
      EnvironmentName: 'dev'      
      PlanSku: 'Y1'
      PlanTier: 'Dynamic'

    steps:      
      - name: 'Create and deploy function app'
        uses: Cheranga/GitHubActions/createanddeployfunctionapp@master
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          dotnetVersion: '6.0.x'
          environmentName: 'dev'          
          resourceGroupName: ${{ env.ResourceGroupName }}
          location: ${{ env.ResourceGroupLocation }}
          planSku: ${{ env.PlanSku }}
          planTier: ${{ env.PlanTier }}

  buildanddeploy:
    needs: provision
    name: 'Build and Deploy'
    runs-on: ubuntu-latest      
    steps:
      - name: 'Build and Deploy the Function App'
        uses: Cheranga/GitHubActions/deploydotnetfunctionapp@master
        with:
          credentials: ${{secrets.AZURE_CREDENTIALS}}
          dotnetVersion: '6.0.x'
          functionAppName: '${{env.FunctionAppName}}dev'           