name: Demo.Serverless.Hotels
concurrency: demo-serverless-hotels

on:
  push:
    branches:
      - main
      - feature/**

  workflow_dispatch: 

env:
  PackagePath: './published'
  FunctionAppName: 'ccfunkyhotels'

jobs:
  storageaccount:
    name: 'Create storage account'    
    runs-on: ubuntu-latest    

    env:
      ResourceGroupName: 'rg-cc-funky-hotels-dev'
      ResourceGroupLocation: 'australiasoutheast'                  
      EnvironmentName: 'dev'     

    steps:      
      - name: 'Create storage account'
        uses: Cheranga/GitHubActions/storageaccount@master
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          deploymentName: '${{ github.run_number }}-sg-${{env.FunctionAppName}}${{env.EnvironmentName}}'
          resourceGroupName: ${{env.ResourceGroupName}}
          name: 'sg${{env.FunctionAppName}}${{env.EnvironmentName}}'
          location: ${{ env.ResourceGroupLocation }}
          storageType: 'nonprod'

  appserviceplan:
    name: 'Create app service plan'    
    runs-on: ubuntu-latest    

    env:
      ResourceGroupName: 'rg-cc-funky-hotels-dev'
      ResourceGroupLocation: 'australiasoutheast'                  
      EnvironmentName: 'dev'     

    steps:      
      - name: 'Create app service plan'
        uses: Cheranga/GitHubActions/appserviceplan@master
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          deploymentName: '${{ github.run_number }}-asp-${{env.FunctionAppName}}${{env.EnvironmentName}}'
          resourceGroupName: ${{env.ResourceGroupName}}
          name: 'plan-${{env.FunctionAppName}}${{env.EnvironmentName}}'
          location: ${{ env.ResourceGroupLocation }}
          planType: 'nonprod'          
      
  #     - name: 'Create and deploy function app'
  #       uses: Cheranga/GitHubActions/createanddeployfunctionapp@master
  #       with:
  #         credentials: ${{ secrets.AZURE_CREDENTIALS }}
  #         dotnetVersion: '6.0.x'
  #         environmentName: 'dev'          
  #         resourceGroupName: ${{ env.ResourceGroupName }}
  #         functionAppName: ${{ env.FunctionAppName }}
  #         location: ${{ env.ResourceGroupLocation }}
  #         planTier: ${{ env.PlanTier }}
  #         planSku: ${{ env.PlanSku }}

  # buildanddeploy:
  #   needs: provision
  #   name: 'Build and Deploy'
  #   runs-on: ubuntu-latest      
  #   steps:
  #     - name: 'Build and Deploy the Function App'
  #       uses: Cheranga/GitHubActions/deploydotnetfunctionapp@master
  #       with:
  #         credentials: ${{secrets.AZURE_CREDENTIALS}}
  #         dotnetVersion: '6.0.x'
  #         functionAppName: '${{env.FunctionAppName}}dev'           