name: Demo.Serverless.Hotels
concurrency: demo-serverless-hotels

on:
  push:
    branches:
      - main
      - feature/**

  workflow_dispatch:

env:
  PackagePath: "./published"
  FunctionAppName: "ccfunkyhotels"
  ResourceGroupName: "rg-cc-funky-hotels-dev"
  ResourceGroupLocation: "australiasoutheast"

jobs:
  pipeline:
    name: Build and Deploy Function App
    runs-on: ubuntu-latest
    steps:
      - name: Provision Azure Resources
        uses: Cheranga/GitHubActions/vanillafunctionapp@master
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          deploymentName: '${{ github.run_number }}-${{ env.FunctionAppName }}'
          environmentName: 'dev'
          resourceGroupName: ${{ env.ResourceGroupName }}
          functionAppName: ${{ env.FunctionAppName }}
          location: ${{ env.ResourceGroupLocation }}
          category: 'nonprod'
      
      - name: Setup storage queue
        uses: Cheranga/GitHubActions/storageaccount@master
        env:
          queues: hotel-cancellations
        with:
          credentials: ${{secrets.AZURE_CREDENTIALS}}
          deploymentName: ${{ github.run_number }}-storage-account-updates
          resourceGroupName: ${{ env.ResourceGroupName }}
          name: sg${{ env.FunctionAppName }}dev
          location: ${{env.ResourceGroupLocation}}
          storageType: nonprod
          queues: ${{ env.queues }}
  
      - name: Assign access to the storage queue
        uses: Cheranga/GitHubActions/assignrbactostorage@master
        with:
          deploymentName: ${{ github.run_number }}-assign-rbac
          resourceGroupName: ${{ env.ResourceGroupName }}
          credentials: ${{secrets.AZURE_CREDENTIALS}}
          storageAccountName: sg${{ env.FunctionAppName }}dev
          accessibility: queue_read_write
          friendlyName: ${{ env.FunctionAppName }}
          functionAppName: ${{ env.FunctionAppName }}dev

  
      - name: Update function app settings
        uses: Cheranga/GitHubActions/functionappsettings@master
        with:
          deploymentName: ${{ github.run_number }}-update-functionapp-settings
          resourceGroupName: ${{ env.ResourceGroupName }}
          location: ${{env.ResourceGroupLocation}}
          credentials: ${{secrets.AZURE_CREDENTIALS}}
          functionAppName: ${{ env.FunctionAppName }}dev
          appSettings: ${{ secrets.APP_SETTINGS }}

      - name: Deploy function app code
        uses: Cheranga/GitHubActions/deploydotnetfunctionapp@master
        with:
          credentials: ${{secrets.AZURE_CREDENTIALS}}
          dotnetVersion: 6.0.x
          functionAppName: ${{ env.FunctionAppName }}dev
